version: '3.8'

services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    networks:
      - common-network
    volumes:
      - ./logs:/app/log

networks:
  common-network:
    driver: bridge
