version: '3.8'

services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - redis-container
      - mysql-container
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai  # 设置时区
    networks:
      - common-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis-container:
    image: redis
    env_file:
      - .env.prod
    volumes:
      - ${RD_DATA}:/data
    networks:
      - common-network
    ports:
      - 6379:${RD_PORT}

  mysql-container:
    image: mysql:8.0.39
    env_file:
      - .env.prod
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
      MYSQL_BIND_ADDRESS: 0.0.0.0  # 新增此行
    networks:
      - common-network
    ports:
      - 3307:${DB_PORT} # 显式映射 MySQL 端口
    depends_on:
      - mysql-init

  mysql-init:
    image: busybox
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    command: sh -c "chown -R 999:999 /var/lib/mysql"
    # 初始化服务无需暴露端口或网络

networks:
  common-network:
    driver: bridge
