version: '3.8'

services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - redis-container
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai  # 设置时区
    networks:
      - common-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis-container:
    image: redis
    volumes:
      - ~/data:/data
    networks:
      - common-network
    ports:
      -6379:${RD_PORT}

networks:
  common-network:
    driver: bridge
